# Generated by Django 4.1.7 on 2023-03-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(default='fntnkispqe', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('is_ego', models.BooleanField()),
                ('step', models.IntegerField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chart')),
            ],
        ),
    ]
