# Generated by Django 4.1.7 on 2023-03-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_name',
            field=models.CharField(default='eitdvkdcra', max_length=200, unique=True),
        ),
    ]
