# Generated by Django 4.1.7 on 2023-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_persona_bio_father_persona_bio_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_name',
            field=models.CharField(default='qyortsqohs', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_ego',
            field=models.BooleanField(default=False),
        ),
    ]
